config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins
  root 'static_pages#home'

  get  "apropos" => 'static_pages#apropos'

  get "investir" => 'static_pages#investir'

  get "contact" => 'static_pages#contact'

  get "documents" => 'static_pages#documents'

  get "galerie" => 'static_pages#galerie'

  get "nocity" => 'static_pages#nocity'

  get '/search' , to: 'logement#find_logements'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :logement
    validates :file, presence: true
    mount_uploader :file, ImageUploader

    def thumb
      file.url(:thumb)
    end
end

app/models/logement.rb
class Logement < ActiveRecord::Base
	validates :desc_home, length: { maximum: 100 }

	 mount_uploader :image, ImageUploader
   mount_uploader :image1, ImageUploader
   mount_uploader :image2, ImageUploader
   mount_uploader :image3, ImageUploader
   mount_uploader :image4, ImageUploader
   mount_uploader :image5, ImageUploader

	 rails_admin do
    list do
      field :id
      field :city
      field :capacity
      field :price
      field :image
    end

    edit do
      field :name
      field :price
      field :desc
      field :desc_home
      field :city
      field :postal
      field :country
      field :street
      field :street_number
      field :surface
      field :capacity
      field :bedroom
      field :air_conditioning
      field :image, :carrierwave
      field :image1, :carrierwave
      field :image2, :carrierwave
      field :image3, :carrierwave
      field :image4, :carrierwave
      field :image5, :carrierwave
    end
  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logement_controller.rb
class LogementController < ApplicationController

	def find_logements

	    @logements = Logement.where("lower(city) = ?", params[:city].downcase).order(:desc)
	    
	    if !@logements.empty?

	    	render "static_pages/home"	
	    

	    else

	     render "static_pages/nocity"
	    end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
    @logements = Logement.all

  end

  def apropos
  end

  def investir
  end

  def contact
  end
  
  def documents
  	
  end
  def nocity
    
  end
  
  def galerie
    @logement = Logement.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logement_helper.rb
module LogementHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="google-site-verification" content="_gyb_5iXwC7h_m1xfPTv0juiY7-bRF_co2DNKfBzezo" />
   <title>Domtomimmo</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
   integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

      <!--<%= csrf_meta_tags %>-->
  </head>

  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to "DomTom Immo", root_path, :class => "navbar-brand" %>
      <!--<a class="navbar-brand" href="#">Brand</a>-->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
           <%= form_tag(search_path, method: :get, id: "search-form", role: "search",class:"navbar-form navbar-left" ) do  %>
                <div  id="search" >
                    <%= text_field_tag 'city', nil, placeholder: "Trouver un logement par ville",  type: "text", class:"form-control"%>
                     <button type="submit" class="btn btn-default">Valider</button>
                </div>
            <% end %>

        <li><%= link_to "Notre agence" , apropos_path %></li>
        <li class="number "> <img src="phone.png" class="phone" />   02 62 02 43 31</li>
        <!--<li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
    </nav>
  <div class="container-fluid">
    <%= yield %>



  </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js
      " integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
    </script>
  </body>
</html>

app/views/static_pages/apropos.html.erb
<div class="row">
	<p><h4 class="contact">Nous sommes situé au 30 rue du Presbytère 97410 Saint-pierre. <br>Vous nous contacter également par email <a href="mailto:domtomimmo.com">domtomimmo@gmail.com</a><br>Par téléphone : 02 62 02 43 31</h4></p>
</div>

 <div class="col-md-12" id="map"> 
 	

 	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3716.363885603705!2d55.47501521493793!3d-21.33613748583258!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2182a0ba61426dc5%3A0x1757745503003d96!2s30+Rue+du+Presbyt%C3%A8re%2C+R%C3%A9union!5e0!3m2!1sfr!2sus!4v1459398789789" width="100%" height="600" frameborder="0" style="border:0" allowfullscreen></iframe>
 </div>

app/views/static_pages/contact.html.erb
<h1>StaticPages#Contact</h1>
<p>Find me in app/views/static_pages/apropos.html.erb</p>

app/views/static_pages/documents.html.erb
<div class="text-center">
	<h3>Documents à télécharger</h3>
</div>
<!--<h4><img src="imagetest.png" class="pdf00"></h4>

	<a href="https://www.dropbox.com/s/cnu51ve3diq2eoi/logo_successport_computer.png?dl=0" target="_blank" >Document à télécharger</a>-->
<p>Nos documents seront prochainement téléchargeables.</p>

app/views/static_pages/galerie.html.erb
<div class="row" id="test">
    <div class="col-md-8  ">
      <h3><%= @logement.desc_home.capitalize %> </h3>
    </div>  
  <div class="col-md-12"> 

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
         

          <img src="<%= @logement.image.url %>" alt=""> 
         
          <div class="carousel-caption">
            
          </div>
        </div>
        <div class="item">
          <img src="<%= @logement.image1.url %>" alt=""> 
          <div class="carousel-caption">
            
          </div>
        </div>
        <div class="item">
          <img src="<%= @logement.image2.url %>" alt=""> 
          <div class="carousel-caption">
            ...
          </div>
        </div>
        <div class="item">
          <img src="<%= @logement.image3.url %>" alt=""> 
          <div class="carousel-caption">
            
          </div>
        </div>
      <div class="item">
          <img src="<%= @logement.image4.url %>" alt=""> 
          <div class="carousel-caption">
        
          </div>
        </div>

      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
   </div>

     <div class="row">
       <div class="col-md-12" id="zone_desc">
        <h3>Description du logement / Nbr de pièces <%= @logement.capacity %></h3>
        <h4 class="equipement"><%= @logement.desc.capitalize %></h4>
       </div> 
     </div>

     <div class="row">
      <div class="col-md-12">
       <h4 class="equipement"><%= @logement.surface %> m2 / <%= @logement.bedroom %> Chambres </h4>

      </div>
     </div>
    

  </div>

  <!--<div class="col-md-4" id="pub_investir">
    <h3>Vous souhaitez investir dans l'immobilier ? </h3>
    <div class="text-center"><a href="investir.html"  target= "_blank"  class="btn btn-primary btn-lg active" role="button">Suivez moi</a></div>
  </div>-->
</div>

app/views/static_pages/home.html.erb
<div class="container">
  <!--<div class="row">
    <div class=" col-lg-offset-4 col-lg-6 col-md-8 col-sm-offset-5 col-sm-offset-3 col-xs-10 ">
        <%= form_tag(search_path, method: :get, id: "search-form", role: "search",class:"form-inline" ) do  %>
            <div  id="search" >
                <%= text_field_tag 'city', nil, placeholder: "Trouver un logement",  type: "text", class:"form-control"%>
                 <button type="submit" class="btn btn-default">Valider</button>
            </div>

         <% end %>
    </div>
  </div>-->

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3>Nos logements </h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <div class="row">
          <% @logements.each do |logement| %> <!--link_to "galerie photo" , :id -> logement.id-->
            <div class="col-md-4 col-sm-4 hero-feature">
                <div class="thumbnail">
                    <img src="<%= logement.image.url %>" alt="" class="img_home">
                    <div class="caption">
                        <h5 class="desc_home"><%= logement.city.capitalize %>, <%= logement.desc_home %> </h5>

                        <p>
                            <h5 class="price"><%= logement.price %> € </h5><%= link_to "Plus d'infos" ,galerie_path(:id => logement.id)%>

                        </p>
                    </div>
                </div>
            </div>
          <% end %>



      

        </div>

</div>


    <!-- /.container -->

app/views/static_pages/investir.html.erb
<p>A venir</p>

app/views/static_pages/nocity.html.erb
<h1>Désolé nous n'avons pas logement dans cette ville. :-( </h1>